CREATE TABLE [dbo].[Globals] (
    [Id]       BIGINT           IDENTITY (1, 1) NOT NULL,
    [Name]     NVARCHAR (50)    NOT NULL,
    [Creator]  UNIQUEIDENTIFIER NOT NULL,
    [Session]  UNIQUEIDENTIFIER NOT NULL,
    [Location] UNIQUEIDENTIFIER NOT NULL,
    [Unit]     UNIQUEIDENTIFIER NULL,
    [Point0]   FLOAT (53)       NULL,
    [Point1]   FLOAT (53)       NULL,
    [Point2]   FLOAT (53)       NULL,
    [Point3]   FLOAT (53)       NULL,
    [Point4]   FLOAT (53)       NULL,
    [Point5]   FLOAT (53)       NULL,
    [Point6]   FLOAT (53)       NULL,
    [Point7]   FLOAT (53)       NULL,
    [Point8]   FLOAT (53)       NULL,
    [Point9]   FLOAT (53)       NULL,
    [Point10]  FLOAT (53)       NULL,
    [Point11]  FLOAT (53)       NULL,
    [Point12]  FLOAT (53)       NULL,
    [Point13]  FLOAT (53)       NULL,
    [Point14]  FLOAT (53)       NULL,
    [Point15]  FLOAT (53)       NULL,
    [Point16]  FLOAT (53)       NULL,
    [Point17]  FLOAT (53)       NULL,
    [Point18]  FLOAT (53)       NULL,
    [Point19]  FLOAT (53)       NULL,
    [Point20]  FLOAT (53)       NULL,
    [Point21]  FLOAT (53)       NULL,
    [Point22]  FLOAT (53)       NULL,
    [Point23]  FLOAT (53)       NULL,
    [Point24]  FLOAT (53)       NULL,
    [Point25]  FLOAT (53)       NULL,
    [Point26]  FLOAT (53)       NULL,
    [Geometry_Type] INT    NULL,
    [Method]   NVARCHAR (50)    NULL,
    [Height]   INT              NULL,
    [Width]    INT              NULL,
    [Weight]   INT              NULL,
    [Dimension]   INT        NULL,
    [Coordinate_Dimension] INT NULL, 
    [Spatial_Dimension] INT NULL, 
    [Envelope] [sys].[geometry] NULL, 
    CONSTRAINT [PK_Globals] PRIMARY KEY CLUSTERED ([Id] ASC)
);

