//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemForAll.Session.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Global
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.Guid User { get; set; }
        public System.Guid Session { get; set; }
        public System.Guid Location { get; set; }
        public Nullable<System.Guid> Unit { get; set; }
        public Nullable<int> Geometry_Type { get; set; }
        public string Method { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Dimension { get; set; }
        public Nullable<int> Coordinate_Dimension { get; set; }
        public Nullable<int> Spatial_Dimension { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Envelope { get; set; }
        public Nullable<double> Point0 { get; set; }
        public Nullable<double> Point1 { get; set; }
        public Nullable<double> Point2 { get; set; }
        public Nullable<double> Point3 { get; set; }
        public Nullable<double> Point4 { get; set; }
        public Nullable<double> Point5 { get; set; }
        public Nullable<double> Point6 { get; set; }
        public Nullable<double> Point7 { get; set; }
        public Nullable<double> Point8 { get; set; }
        public Nullable<double> Point9 { get; set; }
        public Nullable<double> Point10 { get; set; }
        public Nullable<double> Point11 { get; set; }
        public Nullable<double> Point12 { get; set; }
        public Nullable<double> Point13 { get; set; }
        public Nullable<double> Point14 { get; set; }
        public Nullable<double> Point15 { get; set; }
        public Nullable<double> Point16 { get; set; }
        public Nullable<double> Point17 { get; set; }
        public Nullable<double> Point18 { get; set; }
        public Nullable<double> Point19 { get; set; }
        public Nullable<double> Point20 { get; set; }
        public Nullable<double> Point21 { get; set; }
        public Nullable<double> Point22 { get; set; }
        public Nullable<double> Point23 { get; set; }
        public Nullable<double> Point24 { get; set; }
        public Nullable<double> Point25 { get; set; }
        public Nullable<double> Point26 { get; set; }
    }
}
