//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemForAll.Session.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> Session { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Location0 { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Globals { get; set; }
        public string Type { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public System.Data.Entity.Spatial.DbGeography Geo { get; set; }
    }
}
