//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemForAll.Session.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorldSystem
    {
        public int Spatial_Reference_Id { get; set; }
        public string Well_Known_Text { get; set; }
        public Nullable<double> Coordinate_System { get; set; }
        public string Datum { get; set; }
        public string Prime_Meridan { get; set; }
        public string Projection { get; set; }
        public string Unit_of_Measure { get; set; }
        public string Authority_Name { get; set; }
        public string Unit_Conversion_Factor { get; set; }
    }
}
